### ISSUE TITLE
unsized_types: TODO list

### ISSUE THREAD

**Issue by japaric** [japaric/rusty-edge#3]
Known issues:
- [x] `struct Rows<'a, T>(&'a Mat<T>)` where `Mat<T>` is an unsized type errors at compile time with "`T` parameter is never used". Variance problem, seems like the compiler is not registering variance constraints when visiting the unsized type declaration.
- [ ] `impl Drop for UnsizedTy` doesn't add a drop flag to the in-memory representation struct.
- [ ] debuginfo is broken, using `-g` = ICE
- [ ] `transmute`-ing 1-word "fat" pointers (like `&CStr === *const c_char`) is broken:

```
Function return type does not match operand type of return inst!
  ret %"raw::CStr" %1
 i64LLVM ERROR: Broken function found, compilation aborted!
```

TODO
- [ ] Metadata encoding/decoding. Otherwise the feature won't work cross-crate
- [ ] rustdoc. It doesn't even compile right now.
- [ ] Well formedness of fat pointers representation: all fields must be `Copy` and `Sized`.
- [ ] `Box<UnsizedTy>` should be a compiler error if `UnsizedTy` doesn't implement the `Drop` trait.
- [ ] Feature gate should forbid _usage_ of unsized types. Right now it only forbids the `unsize type A = B` definition.
- [ ] Add cfail/rpass tests

There still several holes in the implementation, but I intent to fix the ones that prevent me from writing correct code first, then the ones that allow me to write unsound code, and general deICEing, better diagnostics at the end.
